plugin: aws_ec2
regions:
  - us-east-1
  - us-east-2
strict_permissions: False
strict: False
keyed_groups:
  - prefix: tag
    key: tags
hostnames:
  - tag:Name
  - ip_address

compose:
  ansible_host: public_ip_address
