---
- name: create minecraft user
  user:
    name: "{{ MINECRAFT_USER }}"
    home: "{{ INSTALL_ROOT }}"
    create_home: false
    comment: "Minecraft Server Account"
  become: yes

- name: mkdir /opt/minecraft
  file:
    path: "{{ INSTALL_ROOT }}"
    state: directory
  become: yes

- name: copy server.jar to server
  copy:
    src: "server.jar"
    dest: "{{ INSTALL_ROOT }}"
    remote_src: no
  become: yes

- name: change ownership of installation root
  file:
    path: "{{INSTALL_ROOT }}"
    owner: "{{ MINECRAFT_USER }}"
    recurse: yes
  become: yes

- name: server.properties
  template:
    src: server_properties.j2
    dest: "{{ INSTALL_ROOT }}/server.properties"
  become: yes

- name: whitelist.json
  copy:
    src: "whitelist.json"
    dest: "{{ INSTALL_ROOT }}"
    remote_src: no
  become: yes

- name: ops.json
  copy:
    src: "ops.json"
    dest: "{{ INSTALL_ROOT }}"
    remote_src: no
  become: yes

- name: first server run (generates eula.txt)
  command: "java -jar server.jar nogui"
  args:
    chdir: "{{ INSTALL_ROOT }}"
  ignore_errors: yes
  become: yes

- name: eula.txt
  lineinfile:
    path: "{{ INSTALL_ROOT }}/eula.txt"
    regexp: ^eula=
    line: eula=TRUE
  become: yes
    
- name: change ownership of installation root
  file:
    path: "{{INSTALL_ROOT }}"
    owner: "{{ MINECRAFT_USER }}"
    group: "{{ MINECRAFT_USER }}"
    recurse: yes
  become: yes

- name: service template
  template:
    src: minecraft_service.j2
    dest: /lib/systemd/system/minecraft.service
  become: yes
  notify: systemd
