# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "12288"
  end

  config.vm.network "forwarded_port", guest: 25565, host: 25565

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "minecraft.yml"
  end
end
